import { SiteFooter } from "./site-footer";
import { SiteHeader } from "./site-header";
import { DiagnosticForm } from "./diagnostic-form";
import { HeroMotion } from "./hero-motion";
export default function Home(){return <main><SiteHeader/><HeroMotion/><section className="editorial-section" id="approach"><p className="eyebrow">НАШ ПОДХОД</p><h2>Два взгляда.<br/>Одна картина проекта.</h2><div className="service-grid"><article id="hard"><div className="service-card-media"><img src="/home/rescue-projects.webp" alt="Выступление на бизнес-игре по проектным переговорам"/></div><span className="eyebrow">01</span><h3>Хардовая сторона</h3><p>Цели, оценки, коммерческие предложения, сроки, бюджет и ответственность. Проверяем логику проектных решений и помогаем превратить ожидания в понятные договорённости.</p><a href="/products#workshops">Практические воркшопы</a></article><article id="soft"><div className="service-card-media"><img src="/home/soft-side-new.webp" alt="Екатерина Махновская выступает перед участниками мероприятия"/></div><span className="eyebrow">02</span><h3>Софтовая сторона</h3><p>Доверие, мотивация, скрытые ожидания и сложные разговоры. Помогаем участникам услышать друг друга, обсуждать разногласия и принимать совместные решения.</p><a href="/teams">Синхронизация команд</a></article></div></section><section className="editorial-section"><p className="eyebrow">С ЧЕМ ПОМОГАЕМ</p><div className="service-grid"><article id="grow"><div className="service-card-media"><img src="/home/soft-side.webp" alt="Командная работа участников у флипчартов"/></div><span className="eyebrow">01</span><h3>Развиваем сотрудников</h3><p>прокачиваем продажи, переговоры и навыки управления проектами на практике.</p><a href="/development">Выбрать направление развития</a></article><article id="align"><div className="service-card-media"><img src="/home/align-teams.webp" alt="Команды участвуют в воркшопе по синхронизации проекта"/></div><span className="eyebrow">02</span><h3>Синхронизируем команды</h3><p>Синхронизируем цели, роли и правила взаимодействия команд заказчика и подрядчика.</p><a href="/teams">Объединить команду</a></article><article id="save"><div className="service-card-media"><img src="/home/rescue-projects-new.webp" alt="Участники обсуждают проектную ситуацию на мероприятии IT-Терапии"/></div><span className="eyebrow">03</span><h3>Спасаем проекты</h3><p>Находим причины кризиса и помогаем вернуться к управляемой работе.</p><a href="/rescue">Разобрать ситуацию</a></article></div></section>
    <section className="featured-story" aria-labelledby="astra-case-title"><div className="featured-story-mark"><img src="/clients/astra.png" alt="Astra"/><span>КЕЙС / SYNC</span><a className="featured-story-review" href="/documents/astra-sync-review-1.png" target="_blank" rel="noreferrer" aria-label="Увеличить отзыв Astra о тренинге SYNC"><img src="/documents/astra-sync-review-1.png" alt="Письменный отзыв Astra о тренинге SYNC" width="1273" height="1800" loading="lazy" /></a></div><div className="featured-story-copy"><p className="eyebrow">Синхронизация команд заказчика, методологов и IT-интегратора перед стартом проекта</p><h2 id="astra-case-title">От разных взглядов <br/><span>к общей картине проекта.</span></h2><p>Тренинг SYNC помогает участникам со стороны заказчика и подрядчиков еще до старта проекта договориться о целях, ролях, критериях приемки результатов и правилах разрешения конфликтных ситуаций.</p><dl><div><dt>ЗАДАЧА</dt><dd>Синхронизировать три команды на старте проекта</dd></div><div><dt>ФОРМАТ</dt><dd>Один день, 8 часов, оффлайн</dd></div><div><dt>РЕЗУЛЬТАТ</dt><dd>Команда проекта, синхронизированная по ожиданиям, целям и задачам проекта</dd></div></dl><a href="/cases">Смотреть другие кейсы</a></div></section>
    <section className="team" id="team">
      <div className="section-heading team-heading"><p className="eyebrow">ЭКСПЕРТЫ</p><h2>Два взгляда.<br/>Один результат.</h2><p>Проектная системность встречается с глубокой экспертизой в командной динамике.</p></div>
      <div className="team-grid">
        <article className="person-card"><div className="portrait"><img src="/team/dmitry.png" alt="Дмитрий Шатохин"/></div><div className="person-title"><h3>Дмитрий<br/>Шатохин</h3></div><p className="person-role">IT‑стратег · Руководитель проектов</p><p className="person-principle"><span>ПРИНЦИП РАБОТЫ</span>Превращать ожидания в проверяемые проектные договорённости.</p><ul><li>Сертифицированный руководитель проектов</li><li>16 лет в корпоративном сегменте 1С</li><li>Автор методики оценки проектов на базе 500+ пресейлов</li></ul></article>
        <article className="person-card"><div className="portrait"><img src="/team/ekaterina.png" alt="Екатерина Махновская"/></div><div className="person-title"><h3>Екатерина<br/>Махновская</h3></div><p className="person-role">PCC ICF · Agile Coach · Фасилитатор</p><p className="person-principle"><span>ПРИНЦИП РАБОТЫ</span>Создавать пространство, в котором возможен сложный и честный разговор.</p><ul><li>Профессиональный коуч PCC ICF</li><li>Agile Coach и Agile Facilitator</li><li>Кандидат экономических наук</li></ul></article>
      </div>
    </section><DiagnosticForm/><section className="contact" id="contact"><p className="eyebrow">КОНТАКТЫ</p><h2>Начнём с<br/><span className="accent-text">честного разговора.</span></h2><p className="contact-copy">Если удобнее обсудить задачу напрямую — выберите любой канал связи.</p><div className="contact-actions"><a className="primary-action" href="tel:+79163090129">Позвонить</a><a href="https://wa.me/79163090129" target="_blank" rel="noreferrer">WhatsApp</a><a href="https://t.me/virdsh" target="_blank" rel="noreferrer">Telegram</a><a href="mailto:info@it-therapy.ru">Email</a></div></section><SiteFooter/></main>}
